softwareconstruction240/autograder

- src/main/resources/frontend/src/types/types.ts
- src/main/resources/frontend/src/views/PhaseView/PastSubmissions.vue
pretty simple. It used to be that the "pass/fail" indicator was based purely on if it was over or under 100%. Now it uses the "passed" parameter from the database
> Fixed pass/fail indicator on the left bar of the front end

- .idea/inspectionProfiles/Project_Default.xml
- src/main/java/edu/byu/cs/controller/CasController.java
- src/main/java/edu/byu/cs/server/Server.java
- src/main/resources/config.properties
- src/main/resources/frontend/src/App.vue
- src/main/resources/frontend/src/services/authService.ts
- src/main/resources/frontend/src/views/LoginView.vue
this pull requests adds a front end logout
**Old Behavior:**
to log out, you had to navigate to /auth/logout, which would call a GET rest method on the back end, and return a simple string
**New Behavior**
if you are logged in, next to your name and NetID there is a "Logout" link that calls a POST rest method on the back end, pops up an alert to the user indicating they are logged out, and returns them to the login page. 
This DOES NOT log them out of CAS. The old behavior didn't log them out of CAS either.
> 90 frontend add logout option

- src/main/java/edu/byu/cs/controller/AdminController.java
- src/main/java/edu/byu/cs/honorChecker/HonorCheckerCompiler.java
- src/main/java/edu/byu/cs/server/Server.java
- src/main/java/edu/byu/cs/util/FileUtils.java
- src/main/resources/frontend/src/services/adminService.ts
- src/main/resources/frontend/src/views/AdminView/AdminView.vue
- src/main/resources/frontend/src/views/AdminView/HonorChecker.vue
A tab on the admin page with the option to download a .zip of all the students' repos in a given section.
A new endpoint (`/api/admin/honorChecker/zip/:section`) that connects to a service that given a section number, clones every student's git repo and zips up the revelvant files (the 3 modules, nothing else). The resulting .zip file contains every student's repo without extra code (this results in the .zip files being around 2-3 MB per section instead of 6-7).
> Add Honor Checker File Download

- src/main/java/edu/byu/cs/autograder/Grader.java
- src/main/java/edu/byu/cs/util/DateTimeUtils.java
This PR resolves #126 and also improves the quality of the code in the area directly related to that issue.
Please run and test my code before merging since I don't have a way to run the code locally.
> 126 use full date times for dates

- src/main/java/edu/byu/cs/autograder/Grader.java
[fix pom issue](https://stackoverflow.com/a/30275449) using -DskipTests to skip running tests rather than -Dmaven.test.skip which skips compiling test artifacts, which is why it couldn't find the test artifacts with the pom
> fix pom issue

- src/main/java/edu/byu/cs/autograder/QualityAnalyzer.java
- src/main/java/edu/byu/cs/autograder/TestHelper.java
- src/main/java/edu/byu/cs/util/ProcessUtils.java
This drains both standard out and standard error, and returns the output as an array of strings in case anyone wants the output of standard error (although no code is now)
> Add standard error drain

- src/main/java/edu/byu/cs/util/DateTimeUtils.java
- src/test/java/edu/byu/cs/util/DateTimeUtilsTest.java
This adjusts the late penalty calculations so that weekends are counted as an extra day late (Saturday and Sunday matching the next Monday's calculation rather than the previous Friday's) resolves #214
> Adjust late penalty calculation

- src/main/java/edu/byu/cs/controller/SubmissionController.java
- src/main/java/edu/byu/cs/server/Server.java
- src/main/resources/frontend/package.json
- src/main/resources/frontend/src/services/adminService.ts
- src/main/resources/frontend/src/views/AdminView/AdminView.vue
- src/main/resources/frontend/src/views/AdminView/StudentInfo.vue
- src/main/resources/frontend/src/views/AdminView/Students.vue
- src/main/resources/frontend/yarn.lock
There is now a new tab: "students"
This tab shows a list of all students from the server database, their netID, and a clickable Github URL. Clicking on either the student's name or netID will open up a pop-up window with all of their submissions. (Which you can then open another pop-up in)
> 212 admin add panel for student information

- src/main/java/edu/byu/cs/autograder/PhaseThreeGrader.java
- src/main/java/edu/byu/cs/autograder/TestHelper.java
This commit requires tests exist before compiling (having no tests just means getting a 0 for that rubric item). This also requires phase 3 tests be in the serviceTests folder
> 229 backend verify that tests exist before attempting to compile

- src/main/java/edu/byu/cs/controller/SubmissionController.java
- src/main/java/edu/byu/cs/dataAccess/SubmissionDao.java
- src/main/java/edu/byu/cs/dataAccess/memory/SubmissionMemoryDao.java
- src/main/java/edu/byu/cs/dataAccess/sql/SubmissionSqlDao.java
- src/main/java/edu/byu/cs/server/Server.java
- src/main/resources/frontend/src/services/adminService.ts
- src/main/resources/frontend/src/views/AdminView/SubmissionsView.vue
The Submissions View now only loads the most recent 25 latest submissions. (Latest submission meaning the most recent submission per student per phase). There is now a button at the bottom to load in all latest submissions.
This was done by adding an optional batchSize parameter to the getAllLatestSubmissions() on the DAO that uses a LIMIT statement as suggested by @frozenfrank. 
The specific amount of submissions that is initially loaded is determined by a const in the submissions view, so is easily adjustable.
> Load only 25 Submissions initially

- src/main/java/edu/byu/cs/autograder/score/Scorer.java
This fixes the displayed grade percentage. Currently, the calculation just drops the percentage by 10*x%, where x is the number of days late. This leads to displaying (not grading, grading works correctly) incorrect scores, like 58% instead of 54% for phase 1 extra credit or 33.97% instead of 41.98% for my branch without any phase 3 unit tests and a dock on code quality
> fix score calculation

- src/main/java/edu/byu/cs/autograder/score/Scorer.java
For some reason #256 had a bug that only appeared on the production server where an admin submission wouldn't complete because it tried calling canvas with the admin's netID. This shouldn't have been happening, and it didn't happen during testing, even after the merges. In theory this PR should fix it, by moving the admin-mode check to the beginning of the Scorer call.
> fix admin submission to not call canvas

- src/main/java/edu/byu/cs/autograder/database/DatabaseHelper.java
- src/main/java/edu/byu/cs/autograder/score/Scorer.java
- src/main/java/edu/byu/cs/controller/SubmissionController.java
- src/main/java/edu/byu/cs/controller/netmodel/GradeRequest.java
- src/main/java/edu/byu/cs/model/Phase.java
- src/main/java/edu/byu/cs/util/PhaseUtils.java
- src/main/resources/frontend/src/types/types.ts
- src/main/resources/frontend/src/views/AdminView/SubmissionsView.vue
- src/main/resources/frontend/src/views/HomeView.vue
This adds the ability to run just the quality checker without any phases. 
Must add something like
INSERT INTO autograder.rubric_config (phase, type, category, criteria, points) VALUES ('Quality', 'QUALITY', 'Code Quality', 'Chess Code Quality Rubric (see GitHub)', 30);
to the database for this to work.
closes #225
> 225 run quality checks independent of submitting a phase

- src/main/java/edu/byu/cs/autograder/score/LateDayCalculator.java
Currently running the `LateDayCalculator` tests results in lots of warning messages printed to `System.out`. This change allows for us to still log these warnings, but not pollute standard out
> Use logger instead of System out in `LateDayCalculator`

- src/main/java/edu/byu/cs/util/ProcessUtils.java
- src/main/resources/phases/phase6/passoffTests/serverTests/WebSocketTests.java
This doubles the timeout for tests and lets the tests take longer with websocket messages
> Increase Web Socket time

- src/main/java/edu/byu/cs/util/JwtUtils.java
Currently the secret key for signing tokens is `this_will_be_replaced_with_something_that_is_a_better_secret`; not super ideal.
This PR changes the initial secret key generation to be secure. The downside is that the current frontend doesn't play nicely with this change if the server is restarted while somebody has an unexpired JWT stored.
Instead of fixing our current frontend to handle this, I think this should be a part of @DallinFromEarth's new frontend. Making this work shouldn't be too complicated, it would just require immediately expiring the JWT on the frontend when it becomes invalid. It could be a little tricky to tell the difference between good ol' `unauthorized` and `expired`, so further revisions might need to be made in this PR to accommodate that.
Comments are welcome
> Use secure random key for JWT signing

- .github/workflows/docker-publish.yml
> use updated docker-login action

- README.md
- loki-compose.yml
- pom.xml
- src/main/resources/logback.xml
This PR swaps out `log4j` with `logback`, a more modern logging implementation.
Console logging to `stdout` at `INFO` level
Rolling logs at `WARN` level, rolls at midnight each day
This is the cool one. Loki receives and stores `INFO` levels and displays them using Grafana, which for now will be hosted at `https://cs240.click/loki`
To run Loki locally, you can use the new `loki-compose.yml` file with Docker Compose:
`docker compose -f loki-compose.yml up -d` and access it at http://localhost:3000
This PR removes the need for modifying VM options.
> 318 Use Grafana Loki for logging

- src/main/java/edu/byu/cs/dataAccess/sql/SubmissionSqlDao.java
This PR revises the query that fetches the latest submission for each student-phase. Arguably we don't need this feature anymore, but given that it is still present I wanted to patch our memory overflow error:
`ERROR 1038 (HY001): Out of sort memory, consider increasing server sort buffer size`
I tried <ins>a lot</ins> of different ways to get the query to fallback on indexes, but the conclusion of my research was that indexes are hard.
This PR modifies the query to filter out all the submissions we don't care about _before_ sorting. This technically doesn't fix the problem and mostly just moves the issue further down, but I'd be pretty surprised if we encounter it again, especially if intend on clearing the database each semester
> filter with index before sorting

- src/main/java/edu/byu/cs/autograder/Grader.java
- src/main/java/edu/byu/cs/controller/SubmissionController.java
- src/main/java/edu/byu/cs/server/Server.java
- src/test/java/edu/byu/cs/autograder/GraderTest.java
Strips off trailing characters in github URLs for non-admin submissions. 
Supports SSH urls. 
Addeds test for `cleanRepoUrl` method.
Resolves #125.
> 125 accept divserse repo urls

- src/main/java/edu/byu/cs/autograder/git/GitHelper.java
Previously, the git verification ran for admins, but just was never reported when scoring. However, the commit verification could throw exceptions if the admin had submitted with a different repository in the past. This completely disables the verification for admins so the exception isn't thrown.
> Disable admin commit verification

- src/main/java/edu/byu/cs/autograder/test/PassoffTestGrader.java
- src/main/java/edu/byu/cs/autograder/test/PreviousPhasePassoffTestGrader.java
- src/main/java/edu/byu/cs/autograder/test/TestGrader.java
- src/main/java/edu/byu/cs/util/PhaseUtils.java
The Previous Phase Passoff Test Grader had a bug where extra credit tests were counted as previous tests, and students could not passoff subsequent phases if they didn't have the previous extra credit done. This fixes that.
> Fix previous test grader

- src/main/java/edu/byu/cs/analytics/CommitAnalytics.java
- src/main/java/edu/byu/cs/autograder/git/CommitVerificationResult.java
- src/main/java/edu/byu/cs/autograder/git/GitHelper.java
- src/test/java/edu/byu/cs/autograder/score/ScorerTest.java
The previous code counted only the insertions in each commit. Per the definition we agreed on, this changes it to count both insertions and deletions. This issue will undercount the changes and will affect grading by effectively setting the line change threshold higher.
Additionally, the internal methods were previously reporting the total commits encountered instead of only the substantial commits. This issue does not affect grading.
This does raise a question about definitions. Currently, commits with low change counts still count towards the unique days with commits, even though they do not count towards the substantial commit threshold. This seems fair as it allows a student to do a little setup work on one day, and then do the bulk of the work on a few days. The student still had …
> Correct line counting issue

- src/main/java/edu/byu/cs/autograder/Grader.java
- src/main/java/edu/byu/cs/autograder/git/GitHelper.java
- src/main/java/edu/byu/cs/model/Submission.java
This fixes the null pointer exception that occurred in the commit verification process when students resubmitted their phase after a blocked submission but before it was manually approved.
Beyond simply fixing the error, it also introduces improved error handling so that future errors will be caught and reported, but grading will still continue and the submission can still be saved in the database. Additionally, the call signatures of related functions have been adjusted to minimize the possibility of null pointer issues in the future.
Key adjustments are the titles of each commit in the PR.
This is the sample exception it will resolve:
```bash
java.lang.NullPointerException: Cannot invoke "edu.byu.cs.model.Submission$ScoreVerification.penaltyPct()" because "scoreVerification" is null
at …
```
> Fix commit verification null exception

- src/main/java/edu/byu/cs/autograder/Grader.java
This change is only necessary in one place because of the way the commit verification has been organized.
> Lower commit threshold to 5 changes in discussion with Prof. Wilkerson

- compose.yml
- src/main/java/edu/byu/cs/autograder/Grader.java
- src/main/java/edu/byu/cs/autograder/score/LateDayCalculator.java
- src/main/java/edu/byu/cs/autograder/score/Scorer.java
- src/main/java/edu/byu/cs/properties/ApplicationProperties.java
- src/main/java/edu/byu/cs/server/Server.java
This PR continues efforts begun in #328 by adding guards to newly added method calls. It also leverages the newly added `ApplicationProperties` system to read in the values from a properties file.
> Disable canvas and compilation

- src/main/java/edu/byu/cs/autograder/test/PassoffTestGrader.java
This fixes a calculation where students are receiving notes like "Extra credit tests: +5.6%" (had done 1/2 extra credit) and "Extra credit tests: +2.4%" (had done no extra credit). This will be replaced with the correct number (no extra credit display/4%/8%)
> Only count completed extra credit in notes

- src/main/java/edu/byu/cs/autograder/score/LateDayCalculator.java
- src/test/java/edu/byu/cs/autograder/score/LateDayCalculatorTest.java
Previously, the `LateDayCalculatorTest`'s would generate error output as they intentionally fed poorly formatted data to the functions and tested the results. While we do intend to warn developers as they work on these kinds of adjustments, it is not good practice to have error output hitting the console when the tests run.
The PR introduces a new quiet mode that addresses this problem. The tests use overloads of the methods that enable them to disable the warning output, but the production code still runs with the output enabled.
> Suppress expected warning output in tests

- src/main/java/edu/byu/cs/autograder/Grader.java
- src/main/java/edu/byu/cs/autograder/GradingException.java
- src/main/java/edu/byu/cs/autograder/GradingObserver.java
- src/main/java/edu/byu/cs/autograder/test/PassoffTestGrader.java
- src/main/java/edu/byu/cs/autograder/test/PreviousPhasePassoffTestGrader.java
- src/main/java/edu/byu/cs/autograder/test/TestAnalyzer.java
- src/main/java/edu/byu/cs/autograder/test/TestGrader.java
- src/main/java/edu/byu/cs/autograder/test/TestHelper.java
- src/main/java/edu/byu/cs/autograder/test/TestSuite.java
- src/main/java/edu/byu/cs/autograder/test/UnitTestGrader.java
- src/main/java/edu/byu/cs/controller/SubmissionController.java
- src/main/java/edu/byu/cs/model/Rubric.java
- src/main/java/edu/byu/cs/model/TestAnalysis.java
- src/main/java/edu/byu/cs/model/TestNode.java
- src/main/resources/frontend/src/types/types.ts
- src/main/resources/frontend/src/utils/utils.ts
- src/main/resources/frontend/src/views/StudentView/RubricItemResultsView.vue
- src/test/java/edu/byu/cs/autograder/test/TestAnalyzerTest.java
This fixes the error where student code printing to standard out could intermingle with junit test output and cause tests that passed to appear to fail to the autograder
To fix this, I changed the output of junit from standard out to an xml file and then read from the xml file. This change hopefully changes very little that the students will see (unavoidably the output of parameterized tests looks different now), except extra credit tests are set separate from the rest of tests and displayed at the bottom of test output to give extra distinction between required tests and extra credit tests.
> 375 backend server printing to standard out can intermingle with other test output

- src/main/java/edu/byu/cs/autograder/compile/ModifiedTestFilesVerifier.java
- src/main/java/edu/byu/cs/util/FileUtils.java
Quick bug fix for not running the modified test files verifier on code quality and making a helper method throw a runtime exception instead of returning null.
> Modified test files ignore phase quality

- src/main/java/edu/byu/cs/autograder/test/TestAnalyzer.java
If an exception is thrown from a BeforeAll annotated method junit does not create the output xml file. As a result, an exception is thrown, and the true cause of the error is not reported to the student. This adds a check for the file existing and exits early if it does not. The student will be able to see the stack trace of the error as it will be in the junit process error output
> Fix XML file not created error

- src/main/java/edu/byu/cs/autograder/compile/CompileHelper.java
- src/main/java/edu/byu/cs/autograder/compile/verifers/ServerFacadeTestPortVerifier.java
This adds another verifier that checks for students hardcoding port 8080 and seeing if it can find a line of code matching `port = server.run(0)`. It then warns the student if it can find 8080 somewhere or can't find the target string
> Add verification of running with port argument 0

- src/main/java/edu/byu/cs/autograder/compile/verifers/TestLocationVerifier.java
Added a check to only notify the observer if the message is not blank (instead of potentially warning them with an empty warning message. Yeah, I'm something of a programmer)
> Only display warning if message is not blank in test location verifier

- src/main/java/edu/byu/cs/autograder/Grader.java
- src/main/java/edu/byu/cs/autograder/GradingException.java
- src/main/java/edu/byu/cs/autograder/GradingObserver.java
- src/main/java/edu/byu/cs/autograder/compile/CompileHelper.java
- src/main/java/edu/byu/cs/autograder/compile/StudentCodeReader.java
- src/main/java/edu/byu/cs/autograder/git/GitHelper.java
- src/main/java/edu/byu/cs/autograder/score/Scorer.java
- src/main/java/edu/byu/cs/autograder/test/PreviousPhasePassoffTestGrader.java
- src/main/java/edu/byu/cs/autograder/test/TestHelper.java
- src/main/java/edu/byu/cs/controller/SubmissionController.java
- src/main/java/edu/byu/cs/model/Rubric.java
- src/main/resources/frontend/src/components/MoreInfo.vue
- src/main/resources/frontend/src/views/StudentView/LiveStatus.vue
- src/main/resources/frontend/src/views/StudentView/SubmissionInfo.vue
This adds functionality to record instances of grading issues (compilation issues, previous tests failing) in the submission table so that the students can see that output after closing the tab and the TA's can see that information.
This also fixes a couple of bugs/oversights that were either bothering me or I found while creating this.
@Fiwafoofa I'm not entirely certain of some of the wording. Could you test it out and see if you have any better ideas for some of the messages?
> 382 backend record instances of previous tests failing in submission table

- src/main/java/edu/byu/cs/autograder/Grader.java
- src/main/java/edu/byu/cs/autograder/compile/verifers/ModifiedTestFilesVerifier.java
- src/main/java/edu/byu/cs/autograder/git/GitHelper.java
- src/main/java/edu/byu/cs/autograder/git/GitHubAssignmentGrader.java
- src/main/java/edu/byu/cs/autograder/score/Scorer.java
- src/main/java/edu/byu/cs/autograder/test/GitHubAssignmentGrader.java
- src/main/java/edu/byu/cs/canvas/CanvasIntegrationImpl.java
- src/main/java/edu/byu/cs/model/Phase.java
- src/main/java/edu/byu/cs/model/Rubric.java
- src/main/java/edu/byu/cs/util/PhaseUtils.java
- src/main/resources/frontend/src/stores/uiConfig.ts
- src/main/resources/frontend/src/types/types.ts
- src/main/resources/frontend/src/utils/utils.ts
- src/main/resources/frontend/src/views/AdminView/SubmissionsView.vue
- src/main/resources/frontend/src/views/HomeView.vue
- src/main/resources/frontend/src/views/StudentView/ResultsPreview.vue
- src/main/resources/frontend/src/views/StudentView/RubricItemView.vue
- src/main/resources/frontend/src/views/StudentView/SubmissionInfo.vue
- src/test/java/edu/byu/cs/autograder/git/GitHelperUtils.java
Resolves: https://github.com/softwareconstruction240/autograder/issues/391 
Added backend and frontend support for the autograding for the GitHub assignment. Essentially, student's have to submit their URL to canvas and submit on the autograder to have their assignment autograded. The autograder verifies that the GitHub repo is clonable and there was at least two commits: one for the initialization of the repository and the adding of `notes.md` and if so, grades the assignment based on late penalty (commit penalty is ignored). If not, then their submission is blocked.
Testing was done with these four repos:
* https://github.com/Fiwafoofa/chessWithoutCommit
* https://github.com/Fiwafoofa/chessWithCommit
* https://github.com/Fiwafoofa/chessTA
* …
> 391 autograding for the GitHub assignment

- src/main/java/edu/byu/cs/autograder/score/Scorer.java
Fixed by changing the `applyLatePenalty` method to return a new Rubric rather than alter an existing rubric, then determining score and sending to canvas with the rubric with the penalty applied but generating the submission object with the rubric without the penalty.
Like I said in the issue, can be confusing: 
but hopefully a less confusing and/or a better type of confusing for students
> fix late penalty scores

- src/main/java/edu/byu/cs/analytics/CommitAnalytics.java
- src/main/java/edu/byu/cs/analytics/CommitsByDay.java
- src/main/java/edu/byu/cs/autograder/GradingObserver.java
- src/main/java/edu/byu/cs/autograder/git/CommitVerificationResult.java
- src/main/java/edu/byu/cs/autograder/git/CommitsBetweenBounds.java
- src/main/java/edu/byu/cs/autograder/git/GitHelper.java
- src/main/java/edu/byu/cs/controller/SubmissionController.java
- src/test/java/edu/byu/cs/autograder/git/GitHelperTest.java
- src/test/java/edu/byu/cs/autograder/git/GitHelperUtils.java
- src/test/java/edu/byu/cs/autograder/score/ScorerTest.java
This changes the behavior when errors arise during commit verification. With this change, grading will continue and ultimately report "unverified;" a TA will be able to approve the submission like with other issues.  It also provides additional documentation to prevent future misunderstandings in the future.
This specifically changes the behavior when a student requests grading for a new phase when their previous submission commit is missing. This was happening frequently as students recreated repos between the GitHub phase and Phase 0, typically due to folder issues.
Resolves #420.
> Head hash missing improvement

- src/main/java/edu/byu/cs/controller/UserController.java
Heads up @DallinFromEarth! `UserController:loadCurrentReposIntoUpdateTable()` has an error-handling vulnerability.
I know this is temporary code, but it does have a vulnerability that may cause it to work improperly.
Feel free to close this PR if it's not a concern. Otherwise, build on this PR by pushing to the branch to resolve the concern.
Note that this PR is currently being merged into the `412-expand-url-passing-regex` branch, but this is only temporary. GitHub will automatically update it to merge into `main` when the other PR is merged.
> Provide contextualized note about potential issue with temporary code

- src/test/java/edu/byu/cs/autograder/git/GitHelperTest.java
In the TA meeting today, we breezed over the 200+ lines of meaningful test and pointed out the two tests which have no content. Rookie mistake; my bad.
I didn't implement these tests because they actually function as integration tests and rely on several complex data structures being configured properly.
This PR marks the tests as `@Disabled` so that they do not provide false indicators of success.
> Disable the stubs of integration tests

- src/main/java/edu/byu/cs/dataAccess/sql/ConfigurationSqlDao.java
Some silly goose _me_ forgot to set up the default value of an Instant in the Configuration SQL dao. So that meant it would crash when starting up. This fixes that bug currently on the main branch that came from #466 
Guess I need to do more thorough testing
> add Instant default for config

- src/main/java/edu/byu/cs/autograder/score/Scorer.java
- src/test/java/edu/byu/cs/autograder/score/ScorerTest.java
Oops. I broke it. Now I fixed it.
> Late adjustment patch

- src/main/java/edu/byu/cs/autograder/score/Scorer.java
Fixes the late penalty notes to not add anything if the submission is on time.
> Fix late penalty notes

- src/main/java/edu/byu/cs/autograder/git/GitHelper.java
- src/main/java/edu/byu/cs/service/UserService.java
- src/main/java/edu/byu/cs/util/FileUtils.java
- src/main/java/edu/byu/cs/util/RepoUrlValidator.java
Removed code duplicated from GitHelper and UserService where they would fetch a repo for different reasons but in the same manner. The code to do the repo fetching was made its own method.
RepoUrlValidator's isValid calls this method and does the minimal logic accordingly.
Work consolidating exception handling throughout the process, more importantly within UserService might be possible.
Closes #463
> Extracted Git Logic from UserService into GitHelper

- pom.xml
- src/test/java/edu/byu/cs/util/RepoUrlValidatorTest.java
This PR refactors repetitive tests in the RepoUrlValidatorTests class by converting them to use @ParameterizedTest.
Refactored tests related to the isNotFork functionality by combining them into a single @ParameterizedTest. 
- Covered cases for valid and invalid forks.
Refactored tests for isValidRepoUrl by combining acceptance and rejection cases into a single @ParameterizedTest.
- Valid and invalid URL cases are now handled more compactly.
Adjusted assertions to ensure all scenarios are properly validated.
> Switch to Parameterized Tests in RepoUrlValidatorTests class #504

- src/main/resources/frontend/src/App.vue
Somehow, somewhere, the repo edit button got removed from the student view. This puts it back.
- Put button back
- Reload page upon successful repo change
> Restore student repo edit button

- src/test/java/edu/byu/cs/util/RepoUrlValidatorTest.java
Resolves https://github.com/softwareconstruction240/chess/issues/3, along with all the admin changes that @jerodw helped us accomplish.
**No tests in the Repo will pass until this is merged.**
See an example of the failure message generated from the tests without this change: [Tests Run without fixes](https://github.com/softwareconstruction240/autograder/actions/runs/12816524645)
> Remove tests that require external repos

- src/main/java/edu/byu/cs/autograder/score/LateDayCalculator.java
- src/test/java/edu/byu/cs/autograder/score/LateDayCalculatorTest.java
- src/test/java/edu/byu/cs/autograder/score/MockLateDayCalculator.java
Resolves #511. Inserts checks so that academic holidays can be relied on to be up to date.
This provides a code-level, hard stop detection assertion to verify that academic holiday configuration is not stale. This is a redundant layer to the one @webecke will complete in a more admin friendly manner in #510.
This change will cause errors to be thrown and refuse to perform any grading when the holidays are incorrectly configured. This should enable an admin to quickly identify the error during smoke testing at the beginning of a semester. Helpful error messages are thrown that explain the problem clearly to an admin user.
Hopefully, these checks never need to throw errors, but when they do, it will be a helpful and important reminder that will keep the system running smoothly. This is one …
> 511 verify future holidays are configured

- src/main/java/edu/byu/cs/server/Server.java
- src/test/java/edu/byu/cs/server/ServerTest.java
#483 broke the way the server starts up, preventing the front end from finding the backend. This fixes it.
- Re-states that the backend needs to run on 8080
- Tells the test package to run on port 0, which seems to let it run
>[!Important]
> This is to fix a bug that prevents the proper functioning of the Autograder. It must be merged before the next deployment
> fix endpoint testing bug that prevents server from starting correctly

- src/main/resources/frontend/src/components/RepoEditor.vue
- src/main/resources/frontend/src/network/ServerCommunicator.ts
- src/main/resources/frontend/src/services/userService.ts
It was discovered that on the current main branch, trying to change the repo of yourself as a student would result in a network error. This fixes that.
- Direct front end to call repo update endpoints as a `POST` request
- Remove unused `PATCH` request methods from `ServerCommunicator`
- Rename `UserService` methods to not reference the HTTP method used
When the great and late and beloved @ThanGerlek made his changes with #483 with the endpoint provider and whatnot, he changed the `/api/repo` endpoint to be a `POST` request. However, he didn't tell the front end about this change, and thus we got a 405 error.
When @frozenfrank and others previously talked about making frontend tests and regression tests for the API, I understood they were needed, but couldn't be bothered. After the second …
> Fix bug where repo change requests failed

- src/main/java/edu/byu/cs/autograder/git/CommitValidation/DefaultGitVerificationStrategy.java
- src/main/java/edu/byu/cs/autograder/git/GitHelper.java
- src/test/java/edu/byu/cs/autograder/git/GitHelperTest.java
Upgrades Commit Verification internals to produce an accurate result even when student nuke their repos before Phase 1. Resolves #432.
Although I thought I would need to make some minor modifications to the algorithm, in the end, it appears that we only needed a configuration-type change in `DefaultGitVerificationStrategy`. I see that as a benefit of well designed code!
This PR does update test cases to function with the new paradigm.
While working on this PR, I remembered that the `git` tests work at a low level and never test the integration of `Submission` handling with the git commits together. Future developers could add higher-level, integration-type tests which properly exercise and demonstrate correct behavior of the entire system.
At this point, I do not expect any more students …
> 432 intelligently evaluate history without tail hash

- src/main/java/edu/byu/cs/analytics/CommitAnalytics.java
- src/main/java/edu/byu/cs/analytics/CommitsByDay.java
- src/main/java/edu/byu/cs/autograder/Grader.java
- src/main/java/edu/byu/cs/autograder/git/CommitValidation/CommitVerificationContext.java
- src/main/java/edu/byu/cs/autograder/git/CommitVerificationReport.java
- src/main/java/edu/byu/cs/autograder/git/CommitVerificationResult.java
- src/main/java/edu/byu/cs/autograder/git/GitHelper.java
- src/main/java/edu/byu/cs/autograder/score/Scorer.java
- src/main/java/edu/byu/cs/dataAccess/memory/SubmissionMemoryDao.java
- src/main/java/edu/byu/cs/dataAccess/sql/SqlDb.java
- src/main/java/edu/byu/cs/dataAccess/sql/SubmissionSqlDao.java
- src/main/java/edu/byu/cs/dataAccess/sql/helpers/SqlReader.java
- src/main/java/edu/byu/cs/model/Submission.java
- src/main/java/edu/byu/cs/util/Serializer.java
- src/test/java/edu/byu/cs/autograder/git/GitHelperUtils.java
- src/test/java/edu/byu/cs/autograder/score/ScorerTest.java
Provides the data necessary to surface commit verification results in the web app with knowledge about the specific commits which caused issues for the student. There is enough detail in these new objects to construct a full play by play of each commit authored by the student with links to directly view the commit in GitHub if desired. It also provides debug information should we seek to understand how/why a particular decision was made.
Resolves #519.
- Adds two new columns to the `Submission` table which contain all the commit verification information in JSON.
- The `create table` statements have already been updated
- The necessary ALTER TABLE statements are included here:
```mysql
ALTER TABLE submission
ADD COLUMN commit_context JSON,
ADD COLUMN commit_result JSON;
```
- In the server …
> Provide commit results in submission

- src/main/resources/phases/phase3/passoff/server/StandardAPITests.java
This updates the StandardAPITests in the AutoGrader to the new one merged into the Chess repo from the [Remove Login Bad Request Email Line PR](https://github.com/softwareconstruction240/chess/pull/31).
> Update StandardAPITests to the Fixed One for Login Bad Request

- src/main/java/edu/byu/cs/controller/netmodel/RegisterRequest.java
Resolves #581. The RegisterRequest record, which was used before integration with Canvas setup, is now completely unused and this PR removes it.
> Removed Unused RegisterRequest Record

- src/main/java/edu/byu/cs/autograder/compile/verifers/TestLocationVerifier.java
- src/main/java/edu/byu/cs/util/PhaseUtils.java
This PR:
- Updated the passoffPackagesToTest for phase 0 from "passoff.chess.piece" to "passoff.chess.piecemoves".
- Renamed "unitTestPackagePaths" to "requiredTestPackagePaths" for better accuracy.
> Update Required Packages to Test

- .devcontainer/devcontainer.json
For some reason, building the dev container with the latest version of the maven-sdkman is giving an issue. This PR switches to a previous version where the ZIP file is valid, prevents this issue.
In case anyone is curious what the issue originally was, here is the full log:
```
Connecting to Docker... Cannot connect to the Docker daemon at npipe:////./pipe/docker_engine. Is the docker daemon running?
Connecting to Docker... Connected
Setting up container features:
Downloading maven-sdkman feature manifest...
Downloading node feature manifest...
Creating jb-devcontainer-features-a742d7ef8671c2d6f699a9909d63b4a9...
Building image…
Preparing build context archive…
[==================================================>]14/14 files
Done
Sending build context to Docker daemon… …
```
> Update Devcontainer JSON - Maven SDKMan

- pom.xml
- src/main/resources/phases/pom/pom.xml
Added `org.intellij` and `org.eclipse.jgit` dependencies to submission injected pom.xml.
These dependencies used in the autograder were added to the pom.xml used solely when injected into students' projects when run through the autograder to allow the usage of annotations if the student decided to include them, incurring in any other changes to any students who didn't.
Closes #596 
If we feel like it's needed or desired, we could include these in the pom.xml given through the starter code so they can be used without problems if students decide to use them, but I don't think that is necessary, as it might confuse students. However, most students don't run their project through Maven, so this is a topic for discussion in a separate issue in the correct repository.
Likewise, a note in the …
> Allow annotation dependencies

- src/main/java/edu/byu/cs/autograder/quality/QualityAnalyzer.java
Updates the checkstyle jar with an improvement to the commented code check.
For more information regarding this improvement, read https://github.com/softwareconstruction240/checkstyle/pull/11
> Update Checkstyle Jar
