- src/main/java/edu/byu/cs/autograder/Grader.java
- src/main/java/edu/byu/cs/autograder/TestAnalyzer.java
- src/main/java/edu/byu/cs/controller/SubmissionController.java
prevents the grader from running if the student already has earned the max score
changes include:
- refactoring some code in SubmissionController so that the most recent submission isn't run across duplicate code
- running a check before the grader runs, querying the most recent submission for the phase
> 118 backend deny submissions when the student has earned max score

- src/main/java/edu/byu/cs/analytics/CommitAnalytics.java
- src/main/java/edu/byu/cs/analytics/RunAnalytics.java
- src/main/java/edu/byu/cs/autograder/Grader.java
- src/main/java/edu/byu/cs/canvas/CanvasIntegration.java
- src/main/java/edu/byu/cs/dataAccess/sql/SqlDb.java
- src/main/java/edu/byu/cs/dataAccess/sql/SubmissionSqlDao.java
- src/main/java/edu/byu/cs/model/Submission.java
Work done on this branch includes:
- A service that analyzes commit history of every student
- A check that halts progress on grading a phase if there have been less than 10 commits since their last passoff
> Verify Commits

- src/main/java/edu/byu/cs/autograder/Grader.java
It's only one line, pretty self-explanatory.
> Fix negative score bug

- src/main/resources/frontend/src/views/AdminView/HonorChecker.vue
Not much changed, a type was added to an `event` parameter which originally was `any`.
> Fix TypeScript Build Error

- src/main/java/edu/byu/cs/autograder/Grader.java
- src/main/java/edu/byu/cs/util/DateTimeUtils.java
Reverts softwareconstruction240/autograder#155
This causes some compilation errors due to some variables being out of scope
> Revert "126 use full date times for dates"

- README.md
These instructions reflect the process that @19mdavenport lead me through in order to get started with the project on my local machine. As of yet, I haven't attempted to _grade_ any projects, but only to run the front-end and back-end for other reasons. With that said, the process may not be complete if my code needs to grade code.
While I updated everything that I knew, there were other issues that I didn't know for myself. I've created separate issues (namely #166) to continue the improvement of documentation.
Additionally, while getting set up, there were other unnecessary hurdles that could be minimized in the future. Those have also been noted as separate issues (namely #163, #164, and #165).
Other than that, I feel I did a good job capturing the information that a new person would …
> Add and update getting started instruction

- src/main/java/edu/byu/cs/util/DateTimeUtils.java
This pull request closes #126.
The code is very straightforward, and has been confirmed to build.
> Remove logic that hardcodes the due date to the end of the day

- phases/libs/qualityRubric.json
- src/main/java/edu/byu/cs/autograder/Grader.java
- src/main/java/edu/byu/cs/autograder/PassoffTestGrader.java
- src/main/java/edu/byu/cs/autograder/PhaseOneGrader.java
- src/main/java/edu/byu/cs/autograder/PhaseThreeGrader.java
- src/main/java/edu/byu/cs/autograder/PhaseZeroGrader.java
- src/main/java/edu/byu/cs/autograder/QualityAnalyzer.java
- src/main/java/edu/byu/cs/autograder/TestHelper.java
- src/main/java/edu/byu/cs/canvas/CanvasDeserializer.java
- src/main/java/edu/byu/cs/util/ProcessUtils.java
- src/main/resources/frontend/src/types/types.ts
- src/main/resources/frontend/src/views/PhaseView/RubricTable.vue
Adds functionality for sending rubrics to canvas
> Rubricify canvas

- phases/libs/qualityRubric.json
- src/main/java/edu/byu/cs/autograder/PassoffTestGrader.java
- src/main/java/edu/byu/cs/autograder/QualityAnalyzer.java
- src/main/java/edu/byu/cs/autograder/TestHelper.java
- src/main/java/edu/byu/cs/util/ProcessUtils.java
- src/main/resources/frontend/src/types/types.ts
- src/main/resources/frontend/src/views/PhaseView/RubricTable.vue
Adds static analysis tool check
> Static analysis

- src/main/java/edu/byu/cs/autograder/PassoffTestGrader.java
- src/main/java/edu/byu/cs/autograder/QualityAnalyzer.java
- src/main/resources/frontend/src/views/PhaseView/ResultsPopup.vue
This groups quality errors and warnings together when displayed
> Improve quality messages

- src/main/java/edu/byu/cs/autograder/Grader.java
- src/main/java/edu/byu/cs/canvas/CanvasIntegration.java
- src/main/java/edu/byu/cs/controller/SubmissionController.java
- src/main/java/edu/byu/cs/dataAccess/SubmissionDao.java
- src/main/java/edu/byu/cs/dataAccess/memory/SubmissionMemoryDao.java
- src/main/java/edu/byu/cs/dataAccess/sql/SubmissionSqlDao.java
- src/main/resources/frontend/src/views/PhaseView/ResultsSection.vue
The grade now runs, then checks the score it calculated against the score stored in canvas. If the new score is equal to or lower than the score in canvas, it doesn't save it to canvas, and it notifies the user.
> 124 stop grading if it lowers score

- src/main/java/edu/byu/cs/autograder/Grader.java
- src/main/java/edu/byu/cs/canvas/CanvasIntegration.java
- src/main/java/edu/byu/cs/controller/SubmissionController.java
- src/main/java/edu/byu/cs/dataAccess/SubmissionDao.java
- src/main/java/edu/byu/cs/dataAccess/memory/SubmissionMemoryDao.java
- src/main/java/edu/byu/cs/dataAccess/sql/SubmissionSqlDao.java
- src/main/resources/frontend/src/views/PhaseView/ResultsSection.vue
Reverts softwareconstruction240/autograder#198
> Revert "124 stop grading if it lowers score"

- src/main/java/edu/byu/cs/autograder/QualityAnalyzer.java
This adds the missing warnings section to the results section of the quality
> Add warnings to quality results

- src/main/resources/frontend/package.json
- src/main/resources/frontend/yarn.lock
Michael added the yarn dependency to the branch that this branch came from, so I'm adding it here
> add ag-grid-vue3 yarn dependency

- phases/libs/qualityRubric.json
- src/main/java/edu/byu/cs/autograder/PassoffTestGrader.java
- src/main/java/edu/byu/cs/autograder/QualityAnalyzer.java
- src/main/resources/frontend/src/views/PhaseView/RubricTable.vue
- src/main/resources/frontend/src/views/PhaseView/RubricTableRow.vue
This changes the quality grading categories to be all or nothing rather than each check being a certain number of points
> Adjust quality grading (spring term)

- src/main/java/edu/byu/cs/canvas/CanvasIntegration.java
This adds the ability to submit to canvas on an assignment without overriding the grade, only adding a comment
@frozenfrank requested this feature for #233
> Add ability to send a canvas comment without a grade

- src/main/java/edu/byu/cs/autograder/Grader.java
- src/main/java/edu/byu/cs/autograder/QualityAnalyzer.java
- src/main/java/edu/byu/cs/autograder/TestHelper.java
- src/main/java/edu/byu/cs/controller/SubmissionController.java
- src/main/java/edu/byu/cs/util/ProcessUtils.java
This shifts all process operations to use the ProcessUtils class.
> Always timeout processes

- src/main/java/edu/byu/cs/autograder/DatabaseHelper.java
- src/main/java/edu/byu/cs/autograder/Grader.java
- src/main/java/edu/byu/cs/autograder/GradingException.java
- src/main/java/edu/byu/cs/autograder/PassoffTestGrader.java
- src/main/java/edu/byu/cs/autograder/PhaseFiveGrader.java
- src/main/java/edu/byu/cs/autograder/PhaseFourGrader.java
- src/main/java/edu/byu/cs/autograder/PhaseOneGrader.java
- src/main/java/edu/byu/cs/autograder/PhaseThreeGrader.java
- src/main/java/edu/byu/cs/autograder/PhaseZeroGrader.java
- src/main/java/edu/byu/cs/autograder/QualityAnalyzer.java
- src/main/java/edu/byu/cs/autograder/TestAnalyzer.java
- src/main/java/edu/byu/cs/autograder/TestHelper.java
- src/main/java/edu/byu/cs/controller/SubmissionController.java
- src/main/resources/frontend/src/views/PhaseView/LiveStatus.vue
- src/test/java/edu/byu/cs/autograder/TestAnalyzerTest.java
This adds an output section for viewing packaging errors
> Add packaging error output

- docker-compose.yml
- src/main/java/edu/byu/cs/autograder/Grader.java
- src/main/java/edu/byu/cs/autograder/database/DatabaseHelper.java
- src/main/java/edu/byu/cs/properties/ApplicationProperties.java
- src/main/java/edu/byu/cs/server/Server.java
This adjusts the database helper to use mysql users instead of using the root user and asserting that no new databases were created afterwards.
> Use mysql users

- README.md
> 258 update readme with program arguments (and WSL notes)

- src/main/java/edu/byu/cs/autograder/compile/CompileHelper.java
- src/main/java/edu/byu/cs/autograder/score/Scorer.java
- src/main/java/edu/byu/cs/autograder/test/TestGrader.java
- src/main/java/edu/byu/cs/autograder/test/TestHelper.java
- src/main/java/edu/byu/cs/util/PhaseUtils.java
- src/main/resources/frontend/src/views/AdminView/SubmissionsView.vue
- src/main/resources/frontend/src/views/HomeView.vue
- src/main/resources/phases/pom/client/pom.xml
- src/main/resources/phases/pom/server/pom.xml
- src/main/resources/phases/pom/shared/pom.xml
- src/main/resources/phases/pom/test-dependencies-assembly.xml
This PR adds support for Phase 6 🥳 
```sql
INSERT INTO autograder.rubric_config (phase, type, category, criteria, points) VALUES ('Phase6', 'PASSOFF_TESTS', 'Automated Pass Off Test Cases', 'There are 20 JUnit pass off test cases. Each successful test case is worth 2.5 points.', 50)
INSERT INTO autograder.rubric_config (phase, type, category, criteria, points) VALUES ('Phase6', 'QUALITY', 'Code Quality', 'Chess Code Quality Rubric (see GitHub)', 30)
```
> Add Phase 6 support

- src/main/resources/phases/phase6/passoffTests/serverTests/WebSocketTests.java
Way easier way of doing what the previous pull request did
> Edit wait time

- src/main/java/edu/byu/cs/dataAccess/sql/SqlDb.java
- src/main/java/edu/byu/cs/util/JwtUtils.java
- src/main/resources/phases/phase6/passoffTests/serverTests/WebSocketTests.java
And two other things I think will be necessary or nice
> Index submission table

- src/main/java/edu/byu/cs/honorChecker/HonorCheckerCompiler.java
- src/main/java/edu/byu/cs/util/FileUtils.java
At the request of Dr. Wilkerson, any problematic .zip file is no longer included (as opposed to being an empty .zip file). Additionally, the .zip file names now contain underscores in place of spaces.
> Improve Honor Checker - Requested by Dr. Wilkerson

- Dockerfile
Reverts softwareconstruction240/autograder#311
> Revert "Fix git header bug"

- src/main/resources/logback-test.xml
fixes logback from failing on test runs
> use test logback config

- src/main/java/edu/byu/cs/controller/SubmissionController.java
- src/main/java/edu/byu/cs/dataAccess/ConfigurationDao.java
- src/main/java/edu/byu/cs/dataAccess/DaoService.java
- src/main/java/edu/byu/cs/dataAccess/memory/ConfigurationMemoryDao.java
- src/main/java/edu/byu/cs/dataAccess/sql/ConfigurationSqlDao.java
- src/main/java/edu/byu/cs/dataAccess/sql/SqlDb.java
- src/main/java/edu/byu/cs/server/Server.java
- src/test/java/edu/byu/cs/autograder/score/ScorerTest.java
This PR adds a new table ("configuration") that will allow for a key-value store of application configurations.
For now, this only includes `STUDENT_SUBMISSIONS_ENABLED`. This boolean configuration will allow the autograder to reject student submissions while otherwise allowing all other features to work.
> Add application configuration table

- src/main/java/edu/byu/cs/analytics/CommitAnalytics.java
- src/main/java/edu/byu/cs/analytics/CommitAnalyticsRouter.java
- src/main/java/edu/byu/cs/autograder/TrafficController.java
- src/main/java/edu/byu/cs/autograder/git/GitHelper.java
- src/main/java/edu/byu/cs/autograder/quality/QualityGrader.java
- src/main/java/edu/byu/cs/autograder/score/LateDayCalculator.java
- src/main/java/edu/byu/cs/autograder/score/Scorer.java
- src/main/java/edu/byu/cs/autograder/test/TestGrader.java
- src/main/java/edu/byu/cs/canvas/CanvasUtils.java
- src/main/java/edu/byu/cs/canvas/FakeCanvasIntegration.java
- src/main/java/edu/byu/cs/controller/AdminController.java
- src/main/java/edu/byu/cs/controller/CasController.java
- src/main/java/edu/byu/cs/controller/SubmissionController.java
- src/main/java/edu/byu/cs/controller/WebSocketController.java
- src/main/java/edu/byu/cs/dataAccess/ConfigurationDao.java
- src/main/java/edu/byu/cs/dataAccess/DataAccessException.java
- src/main/java/edu/byu/cs/dataAccess/QueueDao.java
- src/main/java/edu/byu/cs/dataAccess/RubricConfigDao.java
- src/main/java/edu/byu/cs/dataAccess/SubmissionDao.java
- src/main/java/edu/byu/cs/dataAccess/UserDao.java
- src/main/java/edu/byu/cs/dataAccess/sql/ConfigurationSqlDao.java
- src/main/java/edu/byu/cs/dataAccess/sql/QueueSqlDao.java
- src/main/java/edu/byu/cs/dataAccess/sql/RubricConfigSqlDao.java
- src/main/java/edu/byu/cs/dataAccess/sql/SqlDb.java
- src/main/java/edu/byu/cs/dataAccess/sql/SubmissionSqlDao.java
- src/main/java/edu/byu/cs/dataAccess/sql/UserSqlDao.java
- src/main/java/edu/byu/cs/dataAccess/sql/helpers/SqlReader.java
- src/main/java/edu/byu/cs/server/Server.java
- src/test/java/edu/byu/cs/autograder/score/ScorerTest.java
As @frozenfrank pointed out previously, I idiotically made `DataAccessException` a non-checked exception. This lack of foresight on my part has come back to bite one too many times, so this PR fixes that. Unfortunately the fix is by necessity massive in breadth
> Use checked exception for dataaccessexception

- src/main/java/edu/byu/cs/autograder/quality/QualityAnalyzer.java
- src/main/java/edu/byu/cs/autograder/quality/QualityGrader.java
- src/main/resources/phases/libs/qualityRubric.json
Updates to the quality checker for spring 2024
Adds checks for package names and constant names
Removes test case exclusion
Simplifies grading so each category is all or nothing
> spring quality updates

- .gitignore
- src/main/java/edu/byu/cs/honorChecker/HonorCheckerCompiler.java
- src/main/resources/frontend/src/views/AdminView/HonorChecker.vue
This fixes hardcoded section numbers
> Fix ux clean up merge

- src/main/java/edu/byu/cs/autograder/score/Scorer.java
- src/main/java/edu/byu/cs/canvas/model/CanvasRubricAssessment.java
This PR corrects a mathematical issue, and also extracts the GIT_COMMITS rubric manipulation so that the methods can be used in #228 as well.
> Fix lower score bug

- src/main/java/edu/byu/cs/analytics/CommitAnalytics.java
...when they aren't traversed in the original tree.
The original implementation worked for the first submission by a student. However, when traversing a range of commits (which we do for every subsequent submission by a student), the Jgit library would throw an error when attempting to read the heading information from commits which were not included in the original range. This happens on the first commit in the range who's parent is the head hash from the previous submission.
The problem appears to be that JGit only loads the commit information for selected commits, and marks all other as "uninteresting." Uninteresting commits exist and their hashes can be viewed, but no details can be extracted from them. This is what causes the Jgit library to end up throwing a Null-Pointer Exception …
> Load parent commits explicitly 

- src/main/java/edu/byu/cs/util/FileUtils.java
The change is pretty straight forward. 
I found a another implementation of this method, and it's simpler to read as a developer. It uses a different built in Java Object which may bring other implications, but it works just fine for it's purpose.
This PR can be accepted or rejected, and it shouldn't make much of a difference to the end user. If this branch becomes outdated, it would seem more prudent to rebase this on top of the new changes rather than creating a merge commit.
> Simplify implementation of FileUtils.writeStringToFile()

- src/main/java/edu/byu/cs/autograder/Grader.java
- src/main/java/edu/byu/cs/autograder/GradingContext.java
- src/main/java/edu/byu/cs/autograder/GradingObserver.java
- src/main/java/edu/byu/cs/autograder/compile/CompileHelper.java
- src/main/java/edu/byu/cs/autograder/compile/ModuleIndependenceVerifier.java
- src/main/java/edu/byu/cs/autograder/compile/PassoffJarModifier.java
- src/main/java/edu/byu/cs/autograder/compile/PomModifier.java
- src/main/java/edu/byu/cs/autograder/compile/ProjectStructureVerifier.java
- src/main/java/edu/byu/cs/autograder/compile/StudentCodeInteractor.java
- src/main/java/edu/byu/cs/autograder/compile/StudentCodeModifier.java
- src/main/java/edu/byu/cs/autograder/compile/StudentCodeReader.java
- src/main/java/edu/byu/cs/autograder/compile/StudentCodeVerifier.java
- src/main/java/edu/byu/cs/autograder/compile/TestFactoryModifier.java
- src/main/java/edu/byu/cs/autograder/git/GitHelper.java
- src/main/java/edu/byu/cs/controller/SubmissionController.java
- src/main/resources/frontend/src/views/AdminView/SubmissionsView.vue
- src/main/resources/frontend/src/views/HomeView.vue
- src/main/resources/frontend/src/views/StudentView/LiveStatus.vue
- src/test/java/edu/byu/cs/autograder/git/GitHelperUtils.java
- src/test/java/edu/byu/cs/autograder/score/ScorerTest.java
Draft PR so people know what I'm working on and collaborate if needed
resolves #365
resolves #366
> check for common issues and provide helpful error messages - package structure and module interdependence

- src/main/java/edu/byu/cs/autograder/compile/TestFactoryModifier.java
This fixes the websocket test timing without requiring a change to the test file itself
> Fix websocket test timing

- src/main/java/edu/byu/cs/autograder/quality/QualityAnalyzer.java
- src/main/java/edu/byu/cs/canvas/CanvasIntegrationImpl.java
- src/main/java/edu/byu/cs/util/PhaseUtils.java
- src/main/resources/phases/libs/qualityRubric.json
- src/main/resources/phases/phase0/passoff/chess/ChessBoardTests.java
- src/main/resources/phases/phase4/passoff/server/DatabaseTests.java
- src/main/resources/phases/phase6/passoff/server/WebSocketTests.java
Updated Quality Checker and Canvas values
TODO: update test files
> Summer2024

- src/main/java/edu/byu/cs/autograder/compile/StudentCodeReader.java
- src/main/java/edu/byu/cs/autograder/compile/verifers/ModifiedTestFilesVerifier.java
- src/main/java/edu/byu/cs/autograder/compile/verifers/ModuleIndependenceVerifier.java
- src/main/java/edu/byu/cs/autograder/compile/verifers/ServerFacadeTestPortVerifier.java
- src/main/java/edu/byu/cs/autograder/compile/verifers/TestLocationVerifier.java
Based off @Fiwafoofa's branch for course ids because I didn't feel like undoing and redoing the rubric_config stuff, as such should not be merged until after it has been merged into main.
Resolves #400
> 400 backend fix issue with verifiers not being able to read files

- src/main/java/edu/byu/cs/autograder/quality/QualityAnalyzer.java
Based off my previous PR and should be merged in after.
Resolves #402
> add check for checkstyle successfully finishing

- src/main/java/edu/byu/cs/autograder/Grader.java
- src/main/java/edu/byu/cs/autograder/git/GitHelper.java
- src/main/java/edu/byu/cs/autograder/git/GitHubAssignmentGrader.java
- src/main/java/edu/byu/cs/util/PhaseUtils.java
- src/main/resources/frontend/src/utils/utils.ts
- src/main/resources/frontend/src/views/StudentView/ResultsPreview.vue
- src/main/resources/frontend/src/views/StudentView/SubmissionInfo.vue
This in theory should fix the issues mentioned in the TA meeting today, where students were getting flagged with not enough commits on the GitHub phase, and the admin approval buttons weren't showing up for the GitHub phase.
I'm having issues getting the autograder authorized with canvas on my own machine, so I haven't been able to test this yet. I would appreciate someone running this locally on their machine when then can.
> 410 backend remove git commit requirements for GitHub phase

- src/main/java/edu/byu/cs/dataAccess/sql/SubmissionSqlDao.java
- src/main/java/edu/byu/cs/util/DateTimeUtils.java
- src/main/java/edu/byu/cs/util/Serializer.java
This contains small adjustments to the code that have no effect on the computation or result.
> Minor adjustments

- compose.yml
I still haven't fully tested to make sure this doesn't break anything else, but this should solve the specific problem with the logs
resolves #421
> Update compose.yml use latest loki image

- src/main/java/edu/byu/cs/autograder/score/LateDayCalculator.java
- src/main/java/edu/byu/cs/autograder/score/Scorer.java
- src/main/java/edu/byu/cs/util/SubmissionUtils.java
This is a spot fix for the problem with late penalties on manually approved submissions. I discussed a more permanent solution with @frozenfrank earlier, but this is a spot fix to hold us over as the more permanent solution will take some time and this is fairly urgent.
> Spot fix: late penalties on manually approved submissions

- src/main/java/edu/byu/cs/autograder/GradingException.java
- src/main/java/edu/byu/cs/autograder/test/PreviousPhasePassoffTestGrader.java
- src/main/java/edu/byu/cs/canvas/CanvasException.java
- src/main/java/edu/byu/cs/controller/SubmissionController.java
- src/main/java/edu/byu/cs/controller/TrafficController.java
- src/main/java/edu/byu/cs/controller/WebSocketController.java
- src/main/java/edu/byu/cs/util/SubmissionUtils.java
This PR contains refactors and adjustments to several existing code files, without affecting functionality. Each of the changes is limited in scope and collectively they result in a better codebase.
Read the commit messages for justifications and explanations of each specific change.
> Code improvements

- src/main/java/edu/byu/cs/controller/UserController.java
When the GitHub URL management was moved from canvas to the Autograder in #425, we needed a little bit of code to add the current student's repos to the table used for tracking repo changes. Since that code has now run, and future semesters will automatically be loaded into the `repo_update` table by other areas of the code, this code no longer needs to exist in the codebase.
> Remove temporary GitHub repo url migratory code

- src/main/resources/frontend/src/components/AboutPage.vue
- src/main/resources/frontend/src/components/AboutPagePerson.vue
This pull request refactors the `AboutPage.vue` component by extracting individual person details into a new `AboutPagePerson.vue` component. This change simplifies the `AboutPage.vue` component and improves code maintainability. Additionally, the styles for person details have been moved to the new component.
> Make a component for the contributors on the About Page

- src/main/java/edu/byu/cs/autograder/quality/QualityAnalyzer.java
- src/main/resources/phases/phase6/passoff/server/WebSocketTests.java
@ThanGerlek @frozenfrank just so you know I did this
> Update jar and tests

- docs/CONTRIBUTING.md
> Proposed "When to Create an Issue" section

- src/main/java/edu/byu/cs/util/NetworkUtils.java
- src/main/java/edu/byu/cs/util/RepoUrlValidator.java
- src/test/java/edu/byu/cs/util/RepoUrlValidatorTest.java
Leverages refactors from #497 to provide detection of "forked" repos required by https://github.com/softwareconstruction240/softwareconstruction/issues/138.
This is the first step in making it significantly easier for students to clone the starter code, while also blocking easy attempts at cheating.
> Enforce no forks

- docs/getting-started/getting-started.md
Step 4 of the getting started instructions referred to setting up the "Server" Run Configuration. The `Server.java` file no longer has a main method and the run configuration has moved into a `Main.java` class. I updated the instructions to reflect this change.
> Update "Getting Started" instructions 

- src/main/java/edu/byu/cs/server/Server.java
- src/main/java/edu/byu/cs/server/endpointprovider/EndpointProvider.java
- src/main/java/edu/byu/cs/server/endpointprovider/EndpointProviderImpl.java
- src/test/java/edu/byu/cs/server/ServerTest.java
- src/test/java/edu/byu/cs/server/endpointprovider/MockEndpointProvider.java
Planning on instantly merging this but thought I'd give the courtesy of making a reviewable PR.
> fix infinite redirects

- src/main/java/edu/byu/cs/autograder/git/CommitVerificationResult.java
- src/main/java/edu/byu/cs/autograder/git/GitHelper.java
James is a silly goose
@frozenfrank Can you think of any potential unfortunate consequences of this change?
> Fix Resubmission error

- src/main/java/edu/byu/cs/controller/SubmissionController.java
- src/main/java/edu/byu/cs/controller/UserController.java
I'm beginning to think Than didn't test this as much as I thought he would have
> fix javalin path params

- src/main/java/edu/byu/cs/autograder/git/CommitVerificationResult.java
- src/main/java/edu/byu/cs/autograder/git/GitHelper.java
- src/main/java/edu/byu/cs/util/Serializer.java
A better fix than #556 with fewer errors
Reverts the previous fix and replaces with a better, more permanent solution
Resolves #558
> 558 fix resubmission error two electric boogaloo

- src/main/resources/frontend/package.json
- src/main/resources/frontend/src/utils/utils.ts
- src/main/resources/frontend/src/views/StudentView/RubricItemResultsView.vue
Made code coverage only visible to admins (TAs) as students were getting confused whether they were getting docked by code coverage.
> Made code coverage visible only to admin

- src/main/java/edu/byu/cs/autograder/test/TestHelper.java
- src/test/java/edu/byu/cs/autograder/test/TestHelperTests.java
These are tests to simply test removeSparkLinens and trimErrorOutput. Added a new file (TestHelperTests) and tested both of those functions. If there is a different way to potentially add these tests in a certain style, I am open to suggestions.
> TestHelper Tests (Issue 554)

- src/main/java/edu/byu/cs/canvas/CanvasException.java
- src/main/java/edu/byu/cs/canvas/CanvasIntegration.java
- src/main/java/edu/byu/cs/canvas/CanvasIntegrationImpl.java
- src/main/java/edu/byu/cs/canvas/CanvasService.java
- src/main/java/edu/byu/cs/canvas/CanvasUtils.java
- src/main/java/edu/byu/cs/canvas/FakeCanvasIntegration.java
- src/main/java/edu/byu/cs/canvas/model/CanvasAssignment.java
- src/main/java/edu/byu/cs/canvas/model/CanvasRubricAssessment.java
- src/main/java/edu/byu/cs/canvas/model/CanvasRubricItem.java
- src/main/java/edu/byu/cs/canvas/model/CanvasSection.java
- src/main/java/edu/byu/cs/canvas/model/CanvasSubmission.java
- src/main/resources/frontend/src/components/AboutPage.vue
In response to issue #564, this pull request adds Javadoc comments for all the classes in the Canvas Module. As in previous pull requests, I would appreciate as much feedback as possible about these comments and their wording!
> Javadocs - Canvas Module

- src/main/java/edu/byu/cs/autograder/Grader.java
- src/main/java/edu/byu/cs/autograder/GradingContext.java
- src/main/java/edu/byu/cs/autograder/GradingException.java
- src/main/java/edu/byu/cs/autograder/GradingObserver.java
- src/main/java/edu/byu/cs/autograder/GradingObserverImpl.java
- src/main/java/edu/byu/cs/autograder/compile/StudentCodeModifier.java
- src/main/java/edu/byu/cs/autograder/compile/StudentCodeVerifier.java
- src/main/java/edu/byu/cs/autograder/compile/modifiers/PassoffJarModifier.java
- src/main/java/edu/byu/cs/autograder/compile/modifiers/PomModifier.java
- src/main/java/edu/byu/cs/autograder/compile/modifiers/TestFactoryModifier.java
- src/main/java/edu/byu/cs/autograder/quality/QualityAnalyzer.java
- src/main/java/edu/byu/cs/autograder/score/Scorer.java
- src/main/java/edu/byu/cs/autograder/score/ScorerHelper.java
- src/main/java/edu/byu/cs/autograder/test/CoverageAnalyzer.java
- src/main/java/edu/byu/cs/autograder/test/PassoffTestGrader.java
- src/main/java/edu/byu/cs/autograder/test/PreviousPhasePassoffTestGrader.java
- src/main/java/edu/byu/cs/autograder/test/QualityGrader.java
- src/main/java/edu/byu/cs/autograder/test/TestGrader.java
- src/main/java/edu/byu/cs/autograder/test/TestSuite.java
- src/main/java/edu/byu/cs/autograder/test/UnitTestGrader.java
In response to issue #564, this pull request adds Javadoc comments for all the classes in the Autograder Module. I would appreciate as much feedback as possible about these comments and their wording!
> Javadocs - Autograder Module

- src/main/resources/phases/phase0/passoff/chess/ChessBoardTests.java
- src/main/resources/phases/phase0/passoff/chess/ChessMoveTests.java
- src/main/resources/phases/phase0/passoff/chess/ChessPieceTests.java
- src/main/resources/phases/phase0/passoff/chess/ChessPositionTests.java
- src/main/resources/phases/phase0/passoff/chess/EqualsTestingUtility.java
- src/main/resources/phases/phase0/passoff/chess/TestUtilities.java
- src/main/resources/phases/phase0/passoff/chess/piecemoves/BishopMoveTests.java
- src/main/resources/phases/phase0/passoff/chess/piecemoves/KingMoveTests.java
- src/main/resources/phases/phase0/passoff/chess/piecemoves/KnightMoveTests.java
- src/main/resources/phases/phase0/passoff/chess/piecemoves/PawnMoveTests.java
- src/main/resources/phases/phase0/passoff/chess/piecemoves/QueenMoveTests.java
- src/main/resources/phases/phase0/passoff/chess/piecemoves/RookMoveTests.java
- src/main/resources/phases/phase1/passoff/chess/EqualsTestingUtility.java
- src/main/resources/phases/phase1/passoff/chess/TestUtilities.java
- src/main/resources/phases/phase1/passoff/chess/extracredit/CastlingTests.java
- src/main/resources/phases/phase1/passoff/chess/game/ChessGameTests.java
- src/main/resources/phases/phase1/passoff/chess/game/FullGameTest.java
- src/main/resources/phases/phase1/passoff/chess/game/GameStatusTests.java
- src/main/resources/phases/phase3/passoff/server/StandardAPITests.java
- src/main/resources/phases/phase4/passoff/server/DatabaseTests.java
- src/main/resources/phases/phase6/passoff/server/TestFactory.java
- src/main/resources/phases/phase6/passoff/server/WebSocketTests.java
The autograder needs the updated passoff tests for Spring 2025. This PR fixes that.
> Update Passoff Tests for Spring 2025

- src/main/java/edu/byu/cs/controller/AdminController.java
- src/main/java/edu/byu/cs/controller/AuthController.java
- src/main/java/edu/byu/cs/controller/CasController.java
- src/main/java/edu/byu/cs/controller/ConfigController.java
- src/main/java/edu/byu/cs/controller/SubmissionController.java
- src/main/java/edu/byu/cs/controller/UserController.java
- src/main/java/edu/byu/cs/controller/WebSocketController.java
- src/main/java/edu/byu/cs/controller/exception/BadRequestException.java
- src/main/java/edu/byu/cs/controller/exception/InternalServerException.java
- src/main/java/edu/byu/cs/controller/exception/ResourceForbiddenException.java
- src/main/java/edu/byu/cs/controller/exception/ResourceNotFoundException.java
- src/main/java/edu/byu/cs/controller/exception/UnauthorizedException.java
- src/main/java/edu/byu/cs/controller/exception/UnprocessableEntityException.java
- src/main/java/edu/byu/cs/controller/exception/WordOfWisdomViolationException.java
- src/main/java/edu/byu/cs/controller/netmodel/ApprovalRequest.java
- src/main/java/edu/byu/cs/controller/netmodel/GradeRequest.java
In response to #564, this pull request adds Javadoc comments to the controller module. As in previous pull requests, I would appreciate as much feedback as possible about these comments and their wording!
~On a related note, I'm not sure why @ThanGerlek called an exception "WordOfWisdomViolationException" and not something like "RepoAlreadyClaimedException".~
Hopefully, I managed to preserve the humor of the `WordOfWisdomViolationException` and still let interested developers be informed what the exception actually does.
> Javadocs - Controller Module

- src/main/java/Main.java
- src/main/java/edu/byu/cs/server/Server.java
- src/main/java/edu/byu/cs/server/endpointprovider/EndpointProvider.java
- src/main/java/edu/byu/cs/server/endpointprovider/EndpointProviderImpl.java
In response to #564, this pull request adds Javadoc comments to the server module. As in previous pull requests, I would appreciate as much feedback as possible about these comments and their wording!
> Javadocs - Server Module

- src/main/java/edu/byu/cs/service/AdminService.java
- src/main/java/edu/byu/cs/service/CasService.java
- src/main/java/edu/byu/cs/service/ConfigService.java
- src/main/java/edu/byu/cs/service/SubmissionService.java
- src/main/java/edu/byu/cs/service/UserService.java
In response to #564, this pull request adds Javadoc comments to the service module. As in previous pull requests, I would appreciate as much feedback as possible about these comments and their structure and wording!
> Javadocs - Service Module

- src/main/java/edu/byu/cs/dataAccess/DaoService.java
- src/main/java/edu/byu/cs/dataAccess/daoInterface/ConfigurationDao.java
- src/main/java/edu/byu/cs/dataAccess/daoInterface/QueueDao.java
- src/main/java/edu/byu/cs/dataAccess/daoInterface/RepoUpdateDao.java
- src/main/java/edu/byu/cs/dataAccess/daoInterface/RubricConfigDao.java
- src/main/java/edu/byu/cs/dataAccess/daoInterface/SubmissionDao.java
- src/main/java/edu/byu/cs/dataAccess/daoInterface/UserDao.java
- src/main/java/edu/byu/cs/dataAccess/sql/SqlDb.java
- src/main/java/edu/byu/cs/dataAccess/sql/helpers/ColumnDefinition.java
- src/main/java/edu/byu/cs/dataAccess/sql/helpers/ItemBuilder.java
- src/main/java/edu/byu/cs/dataAccess/sql/helpers/ResultSetProcessor.java
- src/main/java/edu/byu/cs/dataAccess/sql/helpers/SqlReader.java
- src/main/java/edu/byu/cs/dataAccess/sql/helpers/StatementPreparer.java
- src/main/java/edu/byu/cs/dataAccess/sql/helpers/StatementQueryExecutor.java
- src/main/java/edu/byu/cs/dataAccess/sql/helpers/ValueAccessor.java
In response to #564, this pull request adds Javadoc comments to the dataAccess module. As in previous pull requests, I would appreciate as much feedback as possible about these comments and their structure and wording!
I added Javadoc comments to the DAO interfaces, but not to the Memory or SQL implementations, as I thought it would be self-explanatory what those implementations are doing without the need for Javadoc comments.
> Javadocs - DataAccess Module

- src/main/java/edu/byu/cs/autograder/compile/verifers/TestLocationVerifier.java
- src/main/java/edu/byu/cs/util/DateTimeUtils.java
- src/main/java/edu/byu/cs/util/FileUtils.java
- src/main/java/edu/byu/cs/util/JwtUtils.java
- src/main/java/edu/byu/cs/util/NetworkUtils.java
- src/main/java/edu/byu/cs/util/PhaseUtils.java
- src/main/java/edu/byu/cs/util/ProcessUtils.java
- src/main/java/edu/byu/cs/util/RepoUrlValidator.java
- src/main/java/edu/byu/cs/util/ResourceUtils.java
- src/main/java/edu/byu/cs/util/Serializer.java
- src/main/java/edu/byu/cs/util/SubmissionUtils.java
My final PR in response to #564. I'm finally about done with all these Javadoc comments for the backend!!! Resolves #564, this pull request adds Javadoc comments to the utils module. As always, I would appreciate as much feedback as possible about these comments and their structure and wording!
What am I going to do with my life now that issue #564 is coming to a close...
> Javadocs - Utils Module

- src/main/resources/phases/phase3/passoff/server/StandardAPITests.java
Updates the StandardAPITests file for a more fitting TestUser Constructor in the LoginBadRequest.
@TheDavSmasher, when this PR gets merged in. Could you update the AutoGrader for the Summer term as soon as possible following the "Autograder Admin Instructions/Checklist" file in the TA drive? Thanks!
> Edit Login Bad Request To Use A More Fitting TestUser Constructor

- src/main/java/edu/byu/cs/dataAccess/sql/SqlDb.java
Used a single connection to set up the db and connection pool is initialized after, with a catalog set.
> fix connection pool catalog issues
